### ISSUE TITLE
recurrence experiment

### ISSUE THREAD

**Issue by tower111** [palmtreemodel/PalmTree#4]
Can you public your dataset or dataset formate?
Thanks.

**Comment by iamawhalez** [comment]
I'm also interested in your article . but i can run it without the dataset.  would you like to public your test dataset  or dataset formate？

**Comment by bobbyhaliwela** [comment]
Since this tool is trained using bert-pytorch implementation by codertimo, i think the data format is similar to the dataset format from that repo. Is this correct @SidekickLx? If its correct, maybe the code to prepare such dataset using binary ninja might be helpful for others. Would gladly contribute to prepare the dataset using other reverse engineering tools as well if needed be.

**Comment by SidekickLx** [comment]
Yes I have prepared those code but cannot get access to it right now. Will
release code for cfg and dfg generation later.

**Comment by bobbyhaliwela** [comment]
@SidekickLx Wonderful! Looking forward to it!

**Comment by SidekickLx** [comment]
We have updated the code for CFG, DFG generation as well as intrinsic and extrinsic evaluation. So, this issue will be closed
